name: amazon
description: "Amazon clone app"
publish_to: 'none'
version: 0.2.0+3

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  assorted_layout_widgets: ^9.0.2
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  get_storage: ^2.1.1
  hive_generator: ^2.0.1
  http: ^1.2.1
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  path: ^1.9.0
  razorpay_web: ^1.4.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
