// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVDUUjw0HFKjcuXN_i1UOsQb7pxMnMezY',
    appId: '1:604178995544:web:637cd0fe4c3856aa27ad2d',
    messagingSenderId: '604178995544',
    projectId: 'clone-7833c',
    authDomain: 'clone-7833c.firebaseapp.com',
    databaseURL: 'https://clone-7833c-default-rtdb.firebaseio.com',
    storageBucket: 'clone-7833c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgR7W4_hU10MgekQ00qLf54wJoR-EDBjY',
    appId: '1:604178995544:android:eb1f4937ae6197b727ad2d',
    messagingSenderId: '604178995544',
    projectId: 'clone-7833c',
    databaseURL: 'https://clone-7833c-default-rtdb.firebaseio.com',
    storageBucket: 'clone-7833c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkGCumeLF5R43OvGCQfPAucSws3YtOQ-g',
    appId: '1:604178995544:ios:7712ac18fac82f0927ad2d',
    messagingSenderId: '604178995544',
    projectId: 'clone-7833c',
    databaseURL: 'https://clone-7833c-default-rtdb.firebaseio.com',
    storageBucket: 'clone-7833c.appspot.com',
    iosBundleId: 'com.amazon.clone.amazon',
  );
}
